VCESIM_NAME: ""
DATE_FORMAT: "%m-%d-%Y %H:%M:%S"
INSTALLPATH: ""
LOGPATH: "./vcesim/logs/"
LOGLEVEL: "INFO"
LOGLIFE: 1
DBFILE: "vcesim.db"
WEBSERVER_IP: x.x.x.x
WEBSERVER_PORT: 8080
REMEMBER_COOKIE_DURATION: 30
